name: vqvae
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.7
  - numpy
  - pip
  - matplotlib
  - scikit-learn
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117 >/dev/null
    - torch==1.13.1
    - torchvision==0.14.1+cu117
    - torchaudio==0.13.1
    - nibabel
    - scikit-image