name: vqvae
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - numpy
  - pip
  - matplotlib
  - ipykernel
  - scikit-learn
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117 >/dev/null
    - torch==1.13.1
    - torchmetrics
    - torchvision==0.14.1+cu117
    - torchaudio==0.13.1
    - nibabel
    - h5py
    - scikit-image
    - albumentations
    - tensorboard
    - tqdm
    - wandb
